### ISSUE TITLE
ChowPhaser not supported on Mojave OSX 10.14.6

### ISSUE THREAD

**Issue by allancole** [jatinchowdhury18/ChowPhaser#10]
Hi, I have ChowPhaser installed on my High Sierra MacBook Pro. The standalone, VST and AU versions all work and sound wonderful! 

However, none of them work on my iMac which is running Mojave. With the standalone version, I got an error when I open it as you can see below. 

![image](https://user-images.githubusercontent.com/709581/112349884-7d9c0e00-8c9f-11eb-845c-cbc378c90d58.png)

![image](https://user-images.githubusercontent.com/709581/112350054-a2908100-8c9f-11eb-9903-4280873d44cf.png)

Only the AU versions appear in the Ableton browser and when I try to open them nothing happens and I can’t use the plugin. A similar thing happens in Reason: 
![image](https://user-images.githubusercontent.com/709581/112364152-9b23a480-8cac-11eb-9b05-6dd6333e759a.png)

At first, I though this was a security preferences issue, so I tried [the solution you recommended here](https://github.com/jatinchowdhury18/AnalogTapeModel/issues/119#issuecomment-749240977), but it didn’t fix the issue. 

The website says ChowDSP apps are compatible with “OS X version 10.12 or newer” so it’s odd that it works in Catalina but not Mojave. 

Thanks in advance for your help—love the sound of this thing.

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! I've been upgrading the [build pipeline](https://github.com/Chowdhury-DSP/releases) for my plugins, and unfortunately I've been lagging a bit on making updates for ChowPhaser. For the moment, I've just generated some builds manually. Could you let me know if [these builds](https://github.com/jatinchowdhury18/ChowPhaser/blob/master/bin/ChowPhaser-Mac-1.1.0.zip) work for you?

**Comment by Vladzibor** [comment]
I also do not work for High Sierra - VST, VST3, AU, Standalone - do not work. Very disappointing. Many musicians still work for High Sierra!

**Comment by jatinchowdhury18** [comment]
@Vladzibor, very sorry to hear that! Would you be able to try [these builds](https://github.com/jatinchowdhury18/ChowPhaser/blob/master/bin/ChowPhaser-Mac-1.1.0.zip), and let me know if they work for you?

**Comment by Vladzibor** [comment]
Thanks for the quick response. I downloaded the plugin distribution from
the link you sent me - and the plugin works great. AU, VST, VST3 and
Standalone ver operate. on High Sierra. Thank you and good luck creating
new plugins. I received the previous distribution on pliginboutique.
Cheers

сб, 17 апр. 2021 г. в 23:45, jatinchowdhury18 ***@***.***>:

**Comment by jatinchowdhury18** [comment]
Full installers with support for MacOS 10.12 and up are now available on the [Nightly Builds page](https://chowdsp.com/nightly.html#phaser).

**Comment by allancole** [comment]
Apologies for the delayed response, but both the nightly builds and the most recent installer updates all work as expected on High Sierra. 

Really love what you’re doing. Thanks for keep things updated @jatinchowdhury18 !

**Comment by jatinchowdhury18** [comment]
No worries! Glad to hear that it's now working correctly :).

Thanks,
Jatin
