### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by dromer** [jatinchowdhury18/ChowPhaser#12]
You knew someone was going to ask ;)

**Comment by jatinchowdhury18** [comment]
LV2 builds are now supported on Linux!

To build, first make sure the git submodules are synced and up to date, then:
```bash
$ cmake -Bbuild
$ cmake --build build --config Release --target ChowPhaserMono_LV2 --parallel
$ cmake --build build --config Release --target ChowPhaserStereo_LV2 --parallel
```

You will also need to have the lv2 dependencies installed: `sudo apt-get install lv2-dev`.

Alternatively, the latest [nightly build](https://chowdsp.com/nightly.html#phaser) for Linux also includes the LV2 build.

**Comment by dromer** [comment]
Nice, will see if I can add it to the new MOD toolchain: https://github.com/moddevices/mod-plugin-builder/compare/juce-tests

**Comment by KottV** [comment]
Hi!

Both mono and stereo have the same URI `https://github.com/jatinchowdhury18/ChowPhaser`
LV2 host will take the first one only. I suppose to format add to the URI
```
https://github.com/jatinchowdhury18/ChowPhaserStereo
https://github.com/jatinchowdhury18/ChowPhaserMono
```

I think it safe. URI is for distinguish plugin's name, not for define it's web page :)

**Comment by jatinchowdhury18** [comment]
Ooh, thanks for the catch! I've pushed this fix to `master`.
