### ISSUE TITLE
binary files clogging up git history

### ISSUE THREAD

**Issue by dromer** [jatinchowdhury18/ChowPhaser#13]
Please purge https://github.com/jatinchowdhury18/ChowPhaser/tree/master/bin from the history and use GH releases.

Cloning the repository pulls in ~256MiB of unnecessary history. Build artifacts should not be inside the source tree.
Without this I bet the code-base is magnitudes smaller.

**Comment by jatinchowdhury18** [comment]
The `bin/` directory has now been removed. A fresh clone is now ~31 MiB.

Thanks,
Jatin

**Comment by dromer** [comment]
Super! nearly 10% of what it was before ;)
