### ISSUE TITLE
Cloning fails because of foleys_gui_magic submodule

### ISSUE THREAD

**Issue by Bleuzen** [jatinchowdhury18/ChowPhaser#18]
Hi, currently this repo fails to clone in flatpak (trying to build the collection repo, see https://github.com/Chowdhury-DSP/releases/issues/1#issuecomment-1045106634).
End of the log:

```
Cloning into '/home/elias/_/build/flathub/.flatpak-builder/build/ChowDSP-Plugins-5/ChowPhaser'...
Submodule path 'ChowPhaser': checked out 'f738a7f400891233f4772c26f14403c940e17744'
Cloning into '/home/elias/_/build/flathub/.flatpak-builder/build/ChowDSP-Plugins-5/ChowPhaser/modules/JUCE'...
Submodule path 'modules/JUCE': checked out 'f00a420bc348d79c4688b33b2b905b8ca0f25a3a'
Cloning into '/home/elias/_/build/flathub/.flatpak-builder/build/ChowDSP-Plugins-5/ChowPhaser/modules/foleys_gui_magic'...
fatal: git upload-pack: not our ref 9cab1a439d86cbf7942981b24ab59c60a55b7dcd
fatal: remote error: upload-pack: not our ref 9cab1a439d86cbf7942981b24ab59c60a55b7dcd
fatal: Fetched in submodule path 'modules/foleys_gui_magic', but it did not contain 9cab1a439d86cbf7942981b24ab59c60a55b7dcd. Direct fetching of that commit failed.
fatal: 
Error: module ChowDSP-Plugins: Der Kindprozess wurde mit Status 128 beendet
```

The [`foleys_gui_magic`](https://github.com/jatinchowdhury18/ChowPhaser/blob/f738a7f400891233f4772c26f14403c940e17744/.gitmodules#L6) submodule used here does not contain the commit (`9cab1a439d86cbf7942981b24ab59c60a55b7dcd`) that ChowPhaser is looking for.
GitHub also displays a warning about it:

![image](https://user-images.githubusercontent.com/12885163/154755241-2cb25150-e33d-4611-a810-e3c8b34c9f41.png)

**Comment by jatinchowdhury18** [comment]
This should be fixed now with #19. Thanks!
