### ISSUE TITLE
Compilation error Phaser

### ISSUE THREAD

**Issue by vaesbart** [jatinchowdhury18/ChowPhaser#9]
Hi,

I downloaded 3 repo's (Matrix, Phaser & Tape) to try these plugins on my Ubuntu Studio install. Matrix & Tape compiled and work OK, but Phaser gives me this error (some paths truncated for brevity):

```
cmake --build build/ --config Release

juce_graphics.cpp:106:
... /chowPhaser/modules/JUCE/modules/juce_graphics/geometry/juce_AffineTransform.cpp: In member function ‘juce::AffineTransform juce::AffineTransform::scaled(float, float, float, float) const’:
... /chowPhaser/modules/JUCE/modules/juce_graphics/geometry/juce_AffineTransform.cpp:151:17: internal compiler error: Segmentation fault
151 | AffineTransform AffineTransform::scaled (float factorX, float factorY,
|                 ^~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
gmake[2]: *** [CMakeFiles/ChowPhaserMono.dir/build.make:223: CMakeFiles/ChowPhaserMono.dir/modules/JUCE/modules/juce_graphics/juce_graphics.cpp.o] Error 1
gmake[2]: Leaving directory '/data/bin/scripts/Chow/chowPhaser/build'
gmake[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/ChowPhaserMono.dir/all] Error 2
gmake[1]: Leaving directory '/data/bin/scripts/Chow/chowPhaser/build'
gmake: *** [Makefile:130: all] Error 2
```

TIA,
Bart.

**Comment by jatinchowdhury18** [comment]
Hi Bart,

Thanks for the report! Unfortunately, I've been unable to recreate the issue on my Linux machine (Ubuntu 18.04, GCC 7.4.0). My CI pipeline build for Linux (also Ubuntu 18.04, GCC 9.3.0) seems to [build fine](https://github.com/jatinchowdhury18/ChowPhaser/runs/1758773012?check_suite_focus=true) as well.

Would it be possible to share which compiler version you're using, as well as the CMake configuration command you're using?

Thanks,
Jatin

**Comment by vaesbart** [comment]
Ok, so I'm not really sure what or how, but I just tried compiling again and it worked.
No particular updates I did or anything, it just went through...

But the Phaser plugin doesn't seem to do any processing though, so something is still off on my system.
I only have Mixbus to try atm, which has experimental VST3 support, but I get a lot of crashes.
I'll try to get an error report or something **if** it's actually caused by the plugin.

I'll just list my lib versions here for reference:

**OS**: Ubuntu Studio 20.10 x86_64 (KDE Plasma 5.19.5)
**Kernel**: 5.8.0-41-lowlatency

**cmake** v3.16.3-3
**gcc** v10.2.0
**python** 3.8.6

Dependencies:
- libasound: 1.2.3.2-1
- libxcursor: 1.2.0-2
- libxinerama: 1.1.4-2
- libxrandr: 1.5.2-0
- freeglut3: 2.8.1-6
- libjack: 1.9.14-0
- freetype: 2.10.2
- libcurl4: 7.68.0-1
- libgl: 1.3.2-1
- libXext: 1.3.4-0

**Comment by jatinchowdhury18** [comment]
Very strange, but glad it's compiling!

I wonder if the crashes are caused by the plugin, or by the "experimental" VST3 support... I think Ardour now supports VST3 if you'd like to give it a try with something (hopefully) more stable.

It is also possible to compile VST2 builds, but you will need to supply your own copy of Steinberg's VST2 SDK, since I'm not allowed to distribute it with the rest of the plugin code.
